services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: framework_outbox
      POSTGRES_USER: adm_outbox
      POSTGRES_PASSWORD: Outbox@123!
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U adm_outbox -d framework_outbox" ]
      interval: 5s
      timeout: 5s
      retries: 20
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: adm_rabbitmq
      RABBITMQ_DEFAULT_PASS: Rabbit@123!
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 20
